name: Build Android

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: recursive

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake libvulkan-dev

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'

      - name: Decode Keystore File
        env:
          KEYSTORE: ${{ secrets.KEYSTORE }}
        run: echo "$KEYSTORE" | base64 --decode > android/app/key.jks

      - name: Create key.properties
        run: |
          echo "storeFile=key.jks" > android/key.properties
          echo "storePassword=${{ secrets.STORE_PASSWORD }}" >> android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "releasePassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
          echo "releaseAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties

      - name: Setup Flutter
        run: |
          flutter config --no-analytics
          flutter pub get

      - name: Build APK
        run: |
          flutter build apk -v --split-per-abi

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: maid-android-apk
          path: build/app/outputs/apk/release

      - name: Build appbundle
        run: |
          flutter build appbundle

      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: maid-android-aab
          path: build/app/outputs/bundle/release/app-release.aab
