name: Build Android, Windows and Linux

on:
  push:
    branches:
      - main

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Add Flutter to PATH
        run: echo "./flutter/bin" >> $GITHUB_PATH
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake libvulkan-dev

      - name: Decode Keystore File
        env:
          KEYSTORE: ${{ secrets.KEYSTORE }}
        run: echo "$KEYSTORE" | base64 --decode > android/app/key.jks

      - name: Create key.properties
        run: |
          echo "storeFile=key.jks" > android/key.properties
          echo "storePassword=${{ secrets.STORE_PASSWORD }}" >> android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "releasePassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
          echo "releaseAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties

      - name: Build APK
        run: |
          flutter pub get
          flutter build apk

      - uses: actions/upload-artifact@v4
        with:
          name: maid-android
          path: build/app/outputs/apk/release/app-release.apk
  
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Add Flutter to PATH
        run: echo "./flutter/bin" >> $GITHUB_PATH
        
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build pkg-config libgtk-3-dev libvulkan-dev

      - name: Build Linux App
        run: |
          flutter pub get
          flutter build linux

      - name: Upload Linux Build
        uses: actions/upload-artifact@v4
        with:
          name: maid-linux
          path: build/linux/x64/release/bundle
        
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Add Flutter to PATH
        run: echo "./flutter/bin" >> $GITHUB_PATH
        
      - name: Install dependencies
        run: |
          choco install -y cmake ninja

      - name: Install Vulkan SDK
        uses: humbletim/install-vulkan-sdk@v1.1.1
        with:
          version: latest
          cache: true

      - name: Build Windows App
        run: |
          flutter pub get
          flutter build windows

      - name: Upload Windows Build
        uses: actions/upload-artifact@v4
        with:
          name: maid-windows
          path: build/windows/x64/bundle
