name: Validate Fastlane

on:
  push:
    branches:
      - main
      - dev
    paths:
      - 'fastlane/**'
  pull_request:
    branches:
      - main
      - dev
    paths:
      - 'fastlane/**'

jobs:
  validate_metadata:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ashutoshgngwr/validate-fastlane-supply-metadata@v2
