name: Build Android, Windows and Linux

on:
  push:
    branches:
      - main

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.1'

      - name: Decode Keystore File
        env:
          KEYSTORE: ${{ secrets.KEYSTORE }}
        run: echo "$KEYSTORE" | base64 --decode > android/app/key.jks

      - name: Create key.properties
        run: |
          echo "storeFile=key.jks" > android/key.properties
          echo "storePassword=${{ secrets.STORE_PASSWORD }}" >> android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "releasePassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
          echo "releaseAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties

      - name: Install CMake 3.10.2
        run: |
          wget https://cmake.org/files/v3.10/cmake-3.10.2-Linux-x86_64.sh
          chmod +x cmake-3.10.2-Linux-x86_64.sh
          sudo ./cmake-3.10.2-Linux-x86_64.sh --prefix=/usr/local --skip-license
          rm cmake-3.10.2-Linux-x86_64.sh

      - name: Build APK
        run: |
          flutter pub get
          flutter build apk

      - uses: actions/upload-artifact@v4
        with:
          name: maid-android
          path: build/app/outputs/apk/release/app-release.apk
  
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.1'
        
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build pkg-config libgtk-3-dev

      - name: Build Linux App
        run: |
          flutter pub get
          flutter build linux

      - name: Upload Linux Build
        uses: actions/upload-artifact@v4
        with:
          name: maid-linux
          path: build/linux/x64/release/bundle
        
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.1'
        
      - name: Install dependencies
        run: |
          choco install -y cmake ninja

      - name: Build Windows App
        run: |
          flutter pub get
          flutter build windows

      - name: Upload Windows Build
        uses: actions/upload-artifact@v4
        with:
          name: maid-windows
          path: build/windows/x64/bundle
